# Generated by Django 3.1.2 on 2020-10-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='deleted',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='deleted',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
